name: convert-magnet-to-torrent

on:
  workflow_dispatch:
    inputs:
      magnet_link:
        description: Magnet link to convert
        required: true

jobs:
  convert_to_torrent:
    runs-on: ubuntu-latest
    steps:
      - name: Install aria2
        run: sudo apt-get install -y aria2
      
      - name: Convert magnet link to torrent
        run: |
          aria2c --follow-torrent=false --seed-time=0 "${{ inputs.magnet_link }}"
          mv -v *.torrent converted.torrent
      
      - name: Upload torrent file
        uses: actions/upload-artifact@v4
        with:
          name: converted-torrent
          path: converted.torrent
