name: magnet-to-torrent

on:
  workflow_dispatch:
    inputs:
      magnet_link:
        description: Magnet link to convert
        required: true
      torrent_name:
        description: Name of the resulting torrent file
        required: true
        default: output.torrent

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Install aria2
        run: sudo apt-get update && sudo apt-get install -y aria2

      - name: Convert magnet link to torrent
        run: aria2c --bt-metadata-only=true --bt-save-metadata=true --listen-port=6881 "${{ inputs.magnet_link }}" -o "${{ inputs.torrent_name }}"

      - name: Upload torrent file
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.torrent_name }}
          path: ${{ inputs.torrent_name }}
