name: block 301 Download Magnet Link

on:
  workflow_dispatch:
    inputs:
      magnet_link:
        description: 'Magnet link to download'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Docker image with aria2
        run: docker pull p3terx/aria2-pro

      - name: Run Docker container to download magnet link
        run: |
          docker run -d --name aria2-downloader -v ${{ github.workspace }}/downloads:/downloads p3terx/aria2-pro
          docker exec aria2-downloader aria2c "${{ github.event.inputs.magnet_link }}"

      - name: Stop and remove Docker container
        run: |
          docker stop aria2-downloader
          docker rm aria2-downloader

      - name: Upload files to Storj-IPFS
        run: |
          for file in $(find ./downloads -type f); do
            curl -X POST "https://www.storj-ipfs.com/api/v0/add" \
              -H "Authorization: Basic $(echo -n '${{ secrets.STORJ_USERNAME }}:${{ secrets.STORJ_PASSWORD }}' | base64)" \
              -F file=@"$file"
          done
        env:
          STORJ_USERNAME: ${{ secrets.STORJ_USERNAME }}
          STORJ_PASSWORD: ${{ secrets.STORJ_PASSWORD }}
