name: Download Magnet Link with docker

on:
  workflow_dispatch:  # Allows the action to be triggered manually
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Docker image with aria2
        run: docker pull p3terx/aria2-pro

      - name: Run Docker container to download magnet link
        run: |
          docker run -d --name aria2-downloader -v ${{ github.workspace }}/downloads:/downloads p3terx/aria2-pro
          docker exec aria2-downloader aria2c "MAGNET_LINK"

      - name: Stop and remove Docker container
        run: |
          docker stop aria2-downloader
          docker rm aria2-downloader

      - name: Upload downloaded files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-files
          path: ./downloads
