name: rtorrent Download

on:
  workflow_dispatch:
    inputs:
      magnet_link:
        description: 'Magnet Link to Download'
        required: true
        default: 'magnet:?xt=urn:btih:your-default-magnet-link-here'

jobs:
  download-torrent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rTorrent
        run: |
          sudo apt-get update
          sudo apt-get install rtorrent rtorrent-gtk

      - name: Start rTorrent
        run: |
          rtorrent -c /etc/rtorrent.rc &

      - name: Download Torrent via Magnet Link
        run: |
          rtorrent-remote -c /etc/rtorrent.rc add "${{ github.event.inputs.magnet_link }}"

      - name: Wait for Download to Complete
        run: |
          while [[ -z "$(rtorrent-remote -c /etc/rtorrent.rc status | grep 'Completed')" ]]; do
            sleep 10
          done

      - name: Upload Torrent Files
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-torrent
          path: /tmp/download