name: rtorrent Download Magnet Link

on:
  workflow_dispatch:
    inputs:
      magnet_link:
        description: 'Magnet link to download'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Pull Docker image with rTorrent
        run: docker pull rtorrent/rtorrent-rpc

      - name: Create rTorrent configuration without password
        run: |
          mkdir -p ~/.rtorrent
          echo "rpc-password=" > ~/.rtorrent/rtorrent.rc
          echo "rpc-whitelist=127.0.0.1" >> ~/.rtorrent/rtorrent.rc

      - name: Run Docker container with rTorrent
        run: |
          docker run -d --name rtorrent-downloader -p 8080:8080 -v ${{ github.workspace }}/downloads:/downloads rtorrent/rtorrent-rpc

      - name: Add magnet link to rTorrent
        run: |
          curl -X POST http://localhost:8080/torrent/add?url=${{ github.event.inputs.magnet_link }}

      - name: Wait for download completion (adjust timeout as needed)
        run: |
          while docker exec rtorrent-downloader rtorrent -c "list-torrents | grep 'completed=1'" | grep -q "completed=1"; do
            sleep 10
          done

      - name: Stop and remove Docker container
        run: |
          docker stop rtorrent-downloader
          docker rm rtorrent-downloader

      - name: Upload downloaded files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-files
          path: ./downloads