name: rtorrent Download Magnet Link

on:
  workflow_dispatch:
    inputs:
      magnet_link:
        description: 'Magnet link to download'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Pull Docker image with libtorrent/bytetorrent-client
        run: docker pull libtorrent/bytetorrent-client

      - name: Run Docker container to download magnet link with libtorrent/bytetorrent-client
        run: |
          docker run -d --name libtorrent-downloader -v ${{ github.workspace }}/downloads:/downloads libtorrent/bytetorrent-client
          docker exec libtorrent-downloader rtcontrol --torrent "${{ github.event.inputs.magnet_link }}"

      - name: Stop and remove Docker container
        run: |
          docker stop rtorrent-downloader
          docker rm rtorrent-downloader

      - name: Upload downloaded files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-files
          path: ./downloads
