name: Aria2 Torrent Download and Upload to Storj-IPFS

on:
  workflow_dispatch:
    inputs:
      magnet_link:
        description: 'Magnet Link to Download'
        required: true
        default: 'magnet:?xt=urn:btih:your-default-magnet-link-here'

jobs:
  download-torrent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Aria2
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2

      - name: Download Torrent via Magnet Link
        run: |
          aria2c --dir=./downloads --seed-time=0 "${{ github.event.inputs.magnet_link }}"

      - name: Upload Files to Storj-IPFS
        run: |
          for file in $(find ./downloads -type f); do
            curl -X POST "https://www.storj-ipfs.com/api/v0/add" \
              -H "Authorization: Basic $(echo -n '${{ secrets.STORJ_USERNAME }}:${{ secrets.STORJ_PASSWORD }}' | base64)" \
              -F file=@"$file"
          done
        env:
          STORJ_USERNAME: ${{ secrets.STORJ_USERNAME }}
          STORJ_PASSWORD: ${{ secrets.STORJ_PASSWORD }}

      - name: Upload Torrent Files as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-torrent
          path: ./downloads
