name: Download Magnet Link with WebTorrent

on:
  workflow_dispatch:
    inputs:
      magnet_link:
        description: 'Magnet link to download'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Build Docker image for WebTorrent
        run: docker build -t webtorrent-docker .

      - name: Run WebTorrent in Docker
        run: |
          docker run -d --name webtorrent-downloader -v ${{ github.workspace }}/downloads:/downloads webtorrent-docker
          docker exec webtorrent-downloader webtorrent download "${{ github.event.inputs.magnet_link }}" --out /downloads

      - name: Stop and remove Docker container
        run: |
          docker stop webtorrent-downloader
          docker rm webtorrent-downloader

      - name: Upload downloaded files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: downloaded-files
          path: ./downloads
